<html>
	<script>
		class MultiplicatorUnitFailure extends Error {}
		var primitive_multiply = function(a, b) {
			var num = Math.floor(Math.random() * 5);
			if (num == 0) {
				return (a * b);
			}
			else {
				throw new MultiplicatorUnitFailure("Multiplication Failure")
			}

		};
		var wrapper = function() {
			var returnNum = null;
			while (true) {
				try {
					returnNum = primitive_multiply(2, 3);
					break;
				}
				catch(e) {
					if (e instanceof MultiplicatorUnitFailure) {
						console.log("Try Again");
					}
					else {
						throw e;
					}
				}
			}
			return returnNum;
		};
		console.log(wrapper());
	</script>
</html>